base_dir: ./images/ # Directory in which to search for data files
output_dir: ./output # Directory to output results to
file_ext: .spm # File extension of the data files.
loading:
  channel: Height # Channel to pull data from in the data files.
filter:
  run: true # Options : true, false
  row_alignment_quantile: 0.5 # lower values may improve flattening of larger features
  threshold_method: std_dev # Options : otsu, std_dev, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    below: 10.0 # Threshold for data below the image background
    above: 1.0 # Threshold for data above the image background
  threshold_absolute:
    below: -1.0 # Threshold for data below the image background
    above: 1.0 # Threshold for data above the image background
  gaussian_size: 1.0121397464510862 # Gaussian blur intensity in px
  gaussian_mode: nearest
  # Scar removal parameters. Be careful with editing these as making the algorithm too sensitive may
  # result in ruining legitimate data.
  remove_scars:
    run: false
    removal_iterations: 2 # Number of times to run scar removal.
    threshold_low: 0.250 # lower values make scar removal more sensitive
    threshold_high: 0.666 # lower values make scar removal more sensitive
    max_scar_width: 4 # Maximum thichness of scars in pixels.
    min_scar_length: 16 # Minimum length of scars in pixels.
freqsplit:
  run: true
  edge_width: 0.1 # Width of borders of grains
  cutoff_bounds: [0, 0.2] # Minimum and maximum cutoff points for frequency splitting.
  min_rms: 11 # Minimum roughness mean score of a high-pass after splitting along the cutoff.
segmentation:
  smoothing:
    sigma: 8
  threshold_offset: -0.5 # Amount to change the calculated threshold by for segmentation. Lower thresholds increase sentitivity.
  threshold_block_size: 800 # Size of each block for local thresholding. Lower values increase segmentation sensitivity.
  cleaning:
    area_threshold: 10000 # in nm2.
    disk_radius_factor: 40
  height_bias: 100 # The amount to prioritise lower pixels to the centre when skeletonising a mask.
remove_smears:
    run: true
    smooth_sigma: 1 # How much to smooth the high pass image before comparing gradients
    smear_threshold: 1.8 # Minimum value for y gradient / x gradient in the high pass image, meaning possible smear
    min_smear_size: 175 # in px^2, areas under this value are removed and ignored
    min_smear_area_percent: 6 # Minimum number of identified smear sections to not discount smear removal. If less they are considered to be in error.
    lowpass_threshold: 95 # Minimum horizontal gradient in the low pass image to be marked
