base_dir: ./example images/ # Directory in which to search for data files
output_dir: ./output # Directory to output results to
file_ext: .spm # File extension of the data files.
loading:
  channel: Height # Channel to pull data from in the data files.
fourier:
  run: true
  edge_width: 0.03 # Width of the cutoff in frequency when performing the fourier split, as a fraction of the total frequency range. Higher values make the split less sensitive to cutoff choice.
  cutoff_bounds: [0, 0.3] # Minimum and maximum cutoff points for frequency splitting.
  min_rms: 10 # Minimum roughness mean score of a high-pass after splitting along the cutoff.
segmentation:
  height_bias: 100 # The amount to bias towards lower (darker) points over the centre when skeletonising grain boundary in a mask. 100 means a heavy bias towards the lowest point in a grain boundary.
pruning:
  run: true
  min_line_length: 5 # The minimum length an offshoot can be to not be considered an error and deleted.
  max_connecting_dist: 10 # The maximum distance the end of an offshoot can be to the other side of the grain for it to be considered an unfinished grain boundary and connected.
remove_smears:
    run: true
    smooth_sigma: 1 # How much to smooth the high pass image before comparing gradients
    smear_threshold: 1.9 # Minimum value for y gradient / x gradient in the high pass image, meaning possible smear
    min_smear_size: 175 # in px^2, areas under this value are removed and ignored
    min_smear_area_percent: 6 # Minimum number of identified smear sections to not discount smear removal. If less they are considered to be in error.
    lowpass_threshold: 110 # Minimum horizontal gradient in the low pass image to be marked
